language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

matrix:
  allow_failures:
    php:
      7.0
      hhvm
  fast_finish: true

env:
  - SYMFONY_VERSION="2.7.*" DECODA_VERSION="6.0.*"
  - SYMFONY_VERSION="2.7.*" DECODA_VERSION="6.*"
  - SYMFONY_VERSION="2.8.*" DECODA_VERSION="6.0.*"
  - SYMFONY_VERSION="2.8.*" DECODA_VERSION="6.*"
  - SYMFONY_VERSION="3.0.*" DECODA_VERSION="6.0.*"
  - SYMFONY_VERSION="3.0.*" DECODA_VERSION="6.*"

before_install:
  - composer self-update
  - if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - composer require symfony/symfony:"${SYMFONY_VERSION}" mjohnson/decoda:"${DECODA_VERSION}" --dev --prefer-source

install: composer update --no-interaction

script: phpunit --coverage-clover=clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
  - php vendor/bin/coveralls -v

notifications:
  email:
    - helios.ag@gmail.com
